### ISSUE TITLE
GuavaMetadataPlugin is package-private, cannot be referenced programtically

### ISSUE THREAD

**Issue by cloudshiftchris** [jjohannes/missing-metadata-guava#2]
Am unable to apply plugin programatically (via another plugin) using Kotlin:

This construct:
`plugins.apply(de.jjohannes.gradle.missingmetadata.guava.GuavaMetadataPlugin::class)`

will not compile as GuavaMetadataPlugin is package-private.

Workaround is to stringly-type the reference:

`plugins.apply("de.jjohannes.missing-metadata-guava")`

**Comment by jjohannes** [comment]
Thanks for reporting @cloudshiftchris. This is fixed in `0.3`.
